# Generated by Django 5.1.15 on 2025-12-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_address_studentprofile_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
