# Generated by Django 5.1.15 on 2025-12-08 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('user_registration', 'User Registration'), ('guide_registration', 'Guide Registration Pending'), ('company_registration', 'Company Registration Pending'), ('guide_approved', 'Guide Approved'), ('guide_rejected', 'Guide Rejected'), ('company_approved', 'Company Approved'), ('company_rejected', 'Company Rejected'), ('guide_logout', 'Guide Logged Out'), ('post_liked', 'Post Liked'), ('post_saved', 'Post Saved')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_post_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
