# Generated by Django 5.1.15 on 2025-12-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/exams/'),
        ),
    ]
