# Generated by Django 5.1.15 on 2025-12-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='guide_profiles/'),
        ),
    ]
