# Generated by Django 5.1.15 on 2025-12-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/exams/'),
        ),
    ]
