# Generated by Django 5.1.15 on 2025-12-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='analyzer_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='candidate_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='candidate_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='detected_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='predicted_field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='recommended_courses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='recommended_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='resume_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
